FROM mcr.microsoft.com/devcontainers/jekyll:0-bullseye
# I can run the bundle install at a different time.
# dev containers abstracts away the volume mounting part
# so you can do it manually in the dockerfile or for now just use basic container
# RUN bundle install